name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & test
      run: |
        yarn install
        yarn workspace @anticrm/platform build && \
        yarn workspace @anticrm/platform-core build && \
        yarn workspace @anticrm/platform-core-plugin build && \
        yarn workspace @anticrm/platform-core-model build && \

        yarn workspace @anticrm/platform run test
        yarn workspace @anticrm/platform-core-model run test
        yarn workspace @anticrm/platform-core-i18n run test
        yarn workspace @anticrm/platform-ui run test
    - name: Lint
      run: |
        yarn workspace @anticrm/platform run lint
        yarn workspace @anticrm/platform-core run lint
        yarn workspace @anticrm/platform-core-i18n run lint
        yarn workspace @anticrm/platform-ui run lint
    - name: Run build
      run: |
        yarn workspace @anticrm/dev-boot run build
