name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        yarn install
        yarn workspace @anticrm/platform run test
        yarn workspace @anticrm/platform-core run test
    - name: Run lint
      run: |
        yarn workspace @anticrm/platform run lint
        yarn workspace @anticrm/platform-core run lint
