# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        yarn install
        yarn workspace @anticrm/platform-core run test
        yarn workspace @anticrm/platform-core-i18n run test
        yarn workspace @anticrm/platform-ui run test
